### ISSUE TITLE
Timeouts for ureq usage

### ISSUE THREAD

**Issue by itamarst** [mgrachev/update-informer#17]
* Given networks can have issues, there should probably be some sort of timeouts set on the `ureq` HTTP client.
* The timeouts should be fairly short, since the version check is _not_ the user's goal, it's a nice-to-have.

**Comment by itamarst** [comment]
I am going to suggest changing the API to `UpdateInformer::check_version(&self, timeout: Duration)`.

1. An API with unlimited blocking is broken.
2. Different applications might feel they have different latency budgets depending how long the tool typically runs.

**Comment by mgrachev** [comment]
Thank you for your feedback!

I agree that we need to set up a timeout for checking new versions.
I suggest the following API to do that:
```rust
let informer = UpdateInformer::new(Crates, "repo", "0.1.0")
    .with_interval(Duration::default())
    .with_timeout(Duration::from_secs(15));

informer.check_version();
```

By default, the interval will be once a day (`Duration::from_secs(60 * 60 * 24)`) and the timeout will be 30 seconds.
What do you think about it?

**Comment by itamarst** [comment]
Looks good. Might do slightly shorter timeout but given it'd be configurable not sure it really matters.

**Comment by mgrachev** [comment]
What timeout would be set by default? 15 seconds?
