### ISSUE TITLE
More standardized location for "last-checked" file

### ISSUE THREAD

**Issue by itamarst** [mgrachev/update-informer#18]
On the assumption that `pip` has done the relevant research correctly:

1. For Unix-y systems, use "$XDG_CACHE_HOME/app-name" or fallback to "~/.cache/app-name". (https://github.com/pypa/pip/blob/dec279ecdf8fd2b0f984dd213198635fdbe320c7/src/pip/_vendor/platformdirs/unix.py#L86)
2. For Windows, CSIDL_LOCAL_APPDATA (https://github.com/pypa/pip/blob/dec279ecdf8fd2b0f984dd213198635fdbe320c7/src/pip/_vendor/platformdirs/windows.py#L62)
3. For macOS, "~/Library/Caches/app-name" (https://github.com/pypa/pip/blob/dec279ecdf8fd2b0f984dd213198635fdbe320c7/src/pip/_vendor/platformdirs/macos.py#L37).

**Comment by itamarst** [comment]
https://docs.rs/app_dirs2/ or https://docs.rs/directories/ might have the right API to get this info.

**Comment by itamarst** [comment]
Other problems with current naming scheme:

1. A PyPI package might have same name as Crates package, but they will share same file on disk.
2. In theory files could conflict with files from other tools.
3. GitHub repos only use the name, not the owner, so namespace conflicts are possible (e.g. `user1/fish` and `user2/fish` would both be recorded as file with name `fish`).

My proposal, given cache dir obrained from `app_dirs2` or the like: `{cache_dir}/update-informer/{registry}-{owner}-{name}-{version}` if owner is set, otherwise `{cache_dir}/update-informer/{registry}-{name}-{version}`.

**Comment by itamarst** [comment]
Further reading: it seems the standards on Windows at least involve application developer, which is ... not something the library should set, I guess? So maybe that should be an input.

**Comment by itamarst** [comment]
But... developer name can be optional with `directories`, at least.

**Comment by mgrachev** [comment]
> My proposal, given cache dir obrained from `app_dirs2` or the like: `{cache_dir}/update-informer/{registry}-{owner}-{name}-{version}` if owner is set, otherwise `{cache_dir}/update-informer/{registry}-{name}-{version}`.

Why did you decide to include the version to the file name?
