### ISSUE TITLE
Less fakes in testing strategy

### ISSUE THREAD

**Issue by itamarst** [mgrachev/update-informer#20]
I'm working on branch for #18, all unit tests pass... but running the example CLI  to get a PyPI package is not working. So I would suggest less `#[cfg(test)]` code variants and more just running with the real code paths.

**Comment by mgrachev** [comment]
Do you suggest remove all mocks functions?

**Comment by itamarst** [comment]
As much as possible, unless you already have good mocking library that has maximal realism. Otherwise you tend to end up testing something that doesn't match reality, and tests might pass even if real world code doesn't.

For example of how to not use mocks but deal with shared state, in #21, the application name is hard-coded as `update-informer-rs`. If you make that configurable (and maybe users would like that anyway?), tests could use random value so that each test starts with (mostly) independent state since it would point at different directory.

Even for talking to GitHub etc., in this particular case talking to real services might be fine. One time in a thousand it'll fail, but how much time do you spend working on this library? Chances of it slowing you down are low. (For things you work on every day, I'd probably go with a verified fake—https://pythonspeed.com/articles/verified-fakes/).

**Comment by mgrachev** [comment]
Okay, I don't mind. Let's try to do it.
