### ISSUE TITLE
Put different update checks behind cargo features

### ISSUE THREAD

**Issue by LoganDark** [mgrachev/update-informer#25]
Usually Rust crates don't have PyPI pages, so it would make sense to put that behind an optional feature.

**Comment by mgrachev** [comment]
Yes, you're right. I'll do it soon.

**Comment by itamarst** [comment]
FWIW, the goal of features seems like reducing compile time and dependencies. PyPI support adds no dependencies, and added compile time is miniscule I suspect. Only seems worth adding feature for update checks that actually add additional dependencies.

**Comment by mgrachev** [comment]
@itamarst I guess you're right. It's not worth it.

**Comment by LoganDark** [comment]
> FWIW, the goal of features seems like reducing compile time and dependencies. PyPI support adds no dependencies, and added compile time is miniscule I suspect. Only seems worth adding feature for update checks that actually add additional dependencies.

The goal of features is to allow disabling unneeded functionality. Not just to reduce dependencies. If PyPI support is in a module it's as easy as adding `#[cfg(feature = "pypi")]` to it.

> @itamarst I guess you're right. It's not worth it.

I'd urge you to reconsider, it's extremely easy and provides peace of mind to your users who might not want or need PyPI support.

**Comment by mgrachev** [comment]
> I'd urge you to reconsider, it's extremely easy and provides peace of mind to your users who might not want or need PyPI support.

@LoganDark You convinced me 🙂 I've already done it, but I'll release it on Monday.
